services:
  ghost-5-130-2:
    image: ghost:5.130.2
    container_name: ghost-5-130-2
    restart: unless-stopped
    ports:
      - "2368:2368"
    environment:
      NODE_ENV: development
      url: http://localhost:2368
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      security__staffDeviceVerification: "false"
    volumes:
      - ghost_5_130_2_content:/var/lib/ghost/content

  ghost-6-36-0:
    image: ghost:6.36.0
    container_name: ghost-6-36-0
    restart: unless-stopped
    ports:
      - "2369:2368"
    environment:
      NODE_ENV: development
      url: http://localhost:2369
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      security__staffDeviceVerification: "false"
    volumes:
      - ghost_6_36_0_content:/var/lib/ghost/content

volumes:
  ghost_5_130_2_content:
  ghost_6_36_0_content:
